### ISSUE TITLE
可以把路径中的中文换成英文，能避免一些不必要的报错

### ISSUE THREAD

**Issue by Jiang-Niao** [iamHuFei/HVVault#3]
RT

**Comment by iamHuFei** [comment]
之前是如此，考虑方便索引改了中文，如果有可能话对标佩奇文库。


胡爽
***@***.***

南京信息工程大学
学生
19825061712


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iamHuFei/HVVault"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月14日(星期四) 下午3:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[iamHuFei/HVVault] 可以把路径中的中文换成英文，能避免一些不必要的报错 (Issue #3)





 
RT
